version: "3"

services:
  app-1:
    image: collectd_client:latest
    container_name: collectd_client_1
    restart: unless-stopped
    logging:
      driver: syslog
      options:
        tag: "{{.DaemonName}}.{{.Name}}"
    environment:
            CONFIG: /home/collectd/etc/client.conf.1
    volumes:
      - type: bind
        source: /opt/my_containers/collectd/etc
        target: /home/collectd/etc
        read_only: true
  app-2:
    image: collectd_client:latest
    container_name: collectd_client_2
    restart: unless-stopped
    logging:
      driver: syslog
      options:
        tag: "{{.DaemonName}}.{{.Name}}"
    environment:
            CONFIG: /home/collectd/etc/client.conf.2
    volumes:
      - type: bind
        source: /opt/my_containers/collectd/etc
        target: /home/collectd/etc
        read_only: true

